'use client';
import {useState} from 'react';
type Photo={mimeType:string;data:string};
type Recipe={title:string;description:string;minutes:number;servings:number;ingredients:string[];missing:string[];steps:string[]};
async function prepare(file:File):Promise<Photo>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)) throw Error('Choose JPG, PNG or WebP photos.');
 if(file.size>15000000) throw Error('Each original photo must be under 15 MB.');
 const url=URL.createObjectURL(file);
 try {const img=new Image(); img.src=url; await img.decode(); const scale=Math.min(1,1200/Math.max(img.width,img.height)); const canvas=document.createElement('canvas');canvas.width=img.width*scale;canvas.height=img.height*scale;canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.72).split(',')[1];if(data.length>1100000) throw Error('This photo is too detailed. Please crop it and try again.');return {mimeType:'image/jpeg',data};}finally{URL.revokeObjectURL(url);}
}
export default function Home(){
 const [photos,setPhotos]=useState<Photo[]>([]),[ingredients,setIngredients]=useState<string[]>([]),[entry,setEntry]=useState(''),[diet,setDiet]=useState('Anything'),[minutes,setMinutes]=useState(30),[servings,setServings]=useState(2),[avoid,setAvoid]=useState(''),[recipes,setRecipes]=useState<Recipe[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function request(body:unknown){const res=await fetch('/api/gemini',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error || 'Something went wrong.');return data;}
 async function run(action:'scan'|'recipes'){setError('');setBusy(action);try{const data=await request(action==='scan'?{action,images:photos}:{action,ingredients,diet,minutes,servings,avoid});if(action==='scan'){setIngredients(old=>Array.from(new Set([...old,...data.ingredients])).slice(0,60));setRecipes([]);if(!data.ingredients.length)setError('No ingredients recognized. Try a clearer photo or add them manually.');}else setRecipes(data.recipes);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy('');}}
 return <main><nav><a className="brand" href="/">◒ pantry<span>lens</span></a><span className="nav-note">A little inspiration. Less food waste.</span><span className="badge">✧ Powered by Gemini</span></nav>
 <header><div className="eyebrow">YOUR KITCHEN, FULL OF POSSIBILITIES</div><h1>Something delicious.<br/><em>Already in your fridge.</em></h1><p>Snap your ingredients. Find your inspiration.<br/>Turn what you have into something you’ll love.</p><div className="steps"><span>01 &nbsp; Snap</span><i>—</i><span>02 &nbsp; Review</span><i>—</i><span>03 &nbsp; Cook</span></div></header>
 <div className="workspace"><section className="panel"><div className="section-heading"><span className="number">01</span><div><h2>What’s in your kitchen?</h2><p>A fridge photo, a countertop spread, or a few ingredients.</p></div></div>
 <fieldset disabled={!!busy}><label className="upload"><span className="camera">⌑</span><strong>Drop your next meal into focus</strong><span>Choose up to 3 photos · JPG, PNG or WebP</span><input aria-label="Upload ingredient photos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setError('');if(files.length+photos.length>3){setError('Please use up to 3 photos.');return;}setBusy('upload');try{const next=await Promise.all(files.map(prepare));setPhotos(old=>[...old,...next]);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}/><span className="upload-button">＋ Choose photos</span></label>
 <label className="capture">Or take a photo on your phone <input aria-label="Take an ingredient photo" type="file" accept="image/*" capture="environment" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(photos.length>=3){setError('Please remove a photo first.');return;}setBusy('upload');setError('');try{const p=await prepare(file);setPhotos(old=>[...old,p]);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}/></label>
 {!!photos.length&&<div className="photos">{photos.map((p,i)=><div key={i}><img src={`data:${p.mimeType};base64,${p.data}`} alt={`Ingredient photo ${i+1}`}/><button aria-label={`Remove photo ${i+1}`} onClick={()=>setPhotos(photos.filter((_,j)=>i!==j))}>×</button></div>)}</div>}
 <button className="primary" disabled={!photos.length} onClick={()=>run('scan')}>{busy==='scan'?'Looking at your ingredients…':'✧ Identify ingredients'}</button><p className="fine">Photos are sent to Google Gemini when you identify ingredients.</p>
 <div className="divider"/><h3>Your ingredients <span className="count">{ingredients.length}</span></h3><p className="hint">Review the list, remove mistakes, or add anything we missed.</p><div className="chips">{ingredients.map(item=><button key={item} onClick={()=>{setIngredients(ingredients.filter(x=>x!==item));setRecipes([]);}} aria-label={`Remove ${item}`}>{item} <span>×</span></button>)}</div>
 <form className="add" onSubmit={e=>{e.preventDefault();const items=entry.split(',').map(x=>x.trim()).filter(Boolean);setIngredients(Array.from(new Set([...ingredients,...items])).slice(0,60));setEntry('');setRecipes([]);}}><input aria-label="Add ingredients separated by commas" maxLength={100} value={entry} onChange={e=>setEntry(e.target.value)} placeholder="e.g. tomatoes, eggs, spinach"/><button disabled={!entry.trim()}>Add ＋</button></form></fieldset></section>
 <section className="panel preferences"><div className="section-heading"><span className="number">02</span><div><h2>Make it your kind of meal</h2><p>A few details to find the right fit.</p></div></div><fieldset disabled={!!busy}><label>Eating preference<select value={diet} onChange={e=>setDiet(e.target.value)}>{['Anything','Vegetarian','Vegan','Gluten-free'].map(d=><option key={d}>{d}</option>)}</select></label><div className="two"><label>Time on hand<select value={minutes} onChange={e=>setMinutes(+e.target.value)}>{[15,30,45,60,90].map(m=><option key={m} value={m}>{m} minutes</option>)}</select></label><label>At the table<select value={servings} onChange={e=>setServings(+e.target.value)}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} {n===1?'person':'people'}</option>)}</select></label></div><label>Ingredients to avoid <span className="optional">optional</span><input value={avoid} maxLength={300} onChange={e=>setAvoid(e.target.value)} placeholder="e.g. peanuts, dairy"/></label><div className="tip"><span>✳</span><div><strong>A little less waste. A lot more possibility.</strong><p>We’ll start with what you have and clearly list any extras you need.</p></div></div><button className="primary" disabled={!ingredients.length} onClick={()=>run('recipes')}>{busy==='recipes'?'Dreaming up your next meal…':'Find my recipes →'}</button><p className="fine">Check ingredient labels and recipe suitability for allergies.</p></fieldset></section></div>
 <div role="status" aria-live="polite">{busy==='upload'&&<p className="status">Preparing your photos…</p>}</div>{error&&<p className="error" role="alert">{error}</p>}
 <section className="results"><div className="eyebrow">FROM YOUR PANTRY TO YOUR PLATE</div><h2>{recipes.length?'Your next delicious idea':'Good things are cooking'}</h2>{!recipes.length?<p className="empty">Your recipe ideas will appear here. Start with a photo or a few ingredients above.</p>:<div className="recipe-grid">{recipes.map((r,i)=><article className="recipe" key={i}><div className="recipe-art">{['◒','✳','◈'][i]}<span>RECIPE 0{i+1}</span></div><div className="recipe-body"><p className="eyebrow">{r.minutes} MIN · SERVES {r.servings}</p><h3>{r.title}</h3><p>{r.description}</p><p className="missing">{r.missing.length?`Extras to pick up: ${r.missing.join(', ')}`:'Everything is in your pantry'}</p><details><summary>Let’s cook ↗</summary><h4>Ingredients</h4><ul>{r.ingredients.map((x,j)=><li key={j}>{x}</li>)}</ul><h4>Method</h4><ol>{r.steps.map((x,j)=><li key={j}>{x}</li>)}</ol></details></div></article>)}</div>}</section><footer><a className="brand" href="/">◒ pantry<span>lens</span></a><span>Less guessing. More cooking.</span></footer></main>;
}
