import type {Place, Point} from './planner';
export const buildings:Record<string,Point>={
 'Talley Student Union':{lat:35.7840,lng:-78.6710},'D. H. Hill Library':{lat:35.7873,lng:-78.6695},'SAS Hall':{lat:35.7855,lng:-78.6663},'Withers Hall':{lat:35.7866,lng:-78.6657},'Riddick Hall':{lat:35.7846,lng:-78.6663},'Nelson Hall':{lat:35.7882,lng:-78.6734},'Poe Hall':{lat:35.7847,lng:-78.6821},'Fountain Dining Hall':{lat:35.7865,lng:-78.6772},'Hunt Library':{lat:35.7694,lng:-78.6766},'Engineering Building II':{lat:35.7722,lng:-78.6743},'Engineering Building III':{lat:35.7725,lng:-78.6780},'On the Oval Food Hall':{lat:35.7712,lng:-78.6741}
};
export function resolveLocation(name:string){const key=Object.keys(buildings).find(k=>k.toLowerCase()===name.trim().toLowerCase());if(key)return buildings[key];const venue=places.find(p=>p.location.toLowerCase()===name.trim().toLowerCase()||p.name.toLowerCase()===name.trim().toLowerCase());return venue?{lat:venue.lat,lng:venue.lng}:undefined;}
const dining='https://dining.ncsu.edu/locations/';
export const places:Place[]=[
 {id:'hill',name:'Hill of Beans',location:'D. H. Hill Library, NC State, Raleigh',campus:true,lat:35.7873,lng:-78.6695,price:8,study:true,category:'Coffee + a study break',description:'Grab a coffee or snack, then settle into an appropriate study area at D. H. Hill. Check library food rules.',source:dining,mealPlan:true,diets:['Vegetarian'],color:'sage',icon:'☕'},
 {id:'talley',name:'Talley Student Union',location:'Talley Student Union, NC State, Raleigh',campus:true,lat:35.7840,lng:-78.6710,price:13,study:false,category:'Food court · meet your pack',description:'A central meetup with several food counters and shared seating. A useful starting point when everyone wants something different.',source:dining,mealPlan:true,diets:['Vegetarian','Vegan','Gluten-free'],color:'peach',icon:'🍜'},
 {id:'atrium',name:'Atrium Food Court',location:'Atrium Food Court, NC State, Raleigh',campus:true,lat:35.7870,lng:-78.6688,price:12,study:false,category:'A bite by the Brickyard',description:'A convenient food stop near the Brickyard and D. H. Hill. Check current counters, menus and hours before heading over.',source:dining,mealPlan:true,diets:['Vegetarian'],color:'yellow',icon:'🥗'},
 {id:'fountain',name:'Fountain Dining Hall',location:'Fountain Dining Hall, NC State, Raleigh',campus:true,lat:35.7865,lng:-78.6772,price:15,study:false,category:'Dining hall · sit down together',description:'A campus dining hall option for a longer meal break. Meal access and pricing depend on your plan and the meal period.',source:dining,mealPlan:true,diets:['Vegetarian','Vegan','Gluten-free'],color:'rose',icon:'🍽️'},
 {id:'oval',name:'On the Oval Food Hall',location:'On the Oval Food Hall, NC State, Raleigh',campus:true,lat:35.7712,lng:-78.6741,price:13,study:false,category:'Centennial Campus bites',description:'A food hall stop for Centennial Campus schedules. Pair a meal with a separate study session at nearby Hunt Library.',source:dining,mealPlan:true,diets:['Vegetarian'],color:'peach',icon:'🥙'},
 {id:'joe',name:'Cup A Joe',location:'3100 Hillsborough Street, Raleigh, NC',campus:false,lat:35.7892,lng:-78.6774,price:10,study:true,category:'Off campus · coffee + a notebook',description:'A Hillsborough Street coffee stop for a snack and a study session. Seating, noise and outlets vary; check when you arrive.',source:'https://cupajoe.com/contact/',mealPlan:false,diets:['Vegetarian'],color:'sage',icon:'☕'}
];
